//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2
use crate::types::client::todo::UpdateTodo;
use sea_orm::entity::prelude::*;
use sea_orm::ActiveValue;
use sea_orm::DbErr;
use sea_orm::QueryOrder;
use serde::{Deserialize, Serialize};
use std::vec::Vec;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "todo")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

impl Model {
    pub async fn update(&self, db: &DatabaseConnection) -> Result<Model, DbErr> {
        let todo = Entity::find_by_id(self.id).one(db).await?;
        let mut todo: ActiveModel = todo.expect("[Todo::Model::update] Could not into").into();
        todo.content = ActiveValue::Set(self.content.clone());
        todo.update(db).await
    }
}

pub async fn get(db: &DatabaseConnection) -> Vec<Model> {
    Entity::find()
        .order_by_desc(Column::CreatedAt)
        .all(db)
        .await
        .expect("[Todo::Model::get] Could not await")
}

pub async fn insert(db: &DatabaseConnection, model: &UpdateTodo) -> Result<Model, DbErr> {
    let todo = ActiveModel {
        id: ActiveValue::NotSet,
        content: ActiveValue::Set(model.content.clone()),
        ..Default::default()
    };
    todo.insert(db).await
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
