FROM rust:1.72.0-slim-bookworm

WORKDIR /app

RUN apt-get update && \
    apt-get install -y build-essential \
    default-libmysqlclient-dev \
    libssl-dev \
    pkg-config
RUN cargo install cargo-watch
RUN cargo install sea-orm-cli
RUN rustup component add clippy
RUN rustup component add rustfmt